name: base
channels:
  - conda-forge
dependencies:
  - r-cowplot=1.1.1
  - r-devtools=2.4.3
  - r-kknn=1.3.1
  - r-scales=1.1.1
  - r-shiny=1.7.1
  - r-testthat=3.1.2
  - r-tidymodels=0.1.4
  - r-tidyverse=1.3.1
  - r-tinytex=0.37
  - r-usethis=2.1.5
  - r-vdiffr=1.0.2
  - r-vroom=1.5.7
  - unixodbc=2.3.9
